baseurl = "/"

# Configurazione della lingua

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = false
[languages]
  [languages.it]
    disabled = false
    languageCode = 'it-IT'
    languageDirection = 'ltr'
    languageName = 'Italiano'
    title = 'LEEPPO'
    weight = 1
    [languages.it.params]
      subtitle = 'Scivola nel divertimento'
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'LEEPPO'
    weight = 2
    [languages.en.params]
      subtitle = 'The slippery and the wet'

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]

[params]
images = ["media/og-image.png"]